runtime: python310
entrypoint: gunicorn -b :$PORT run:app

automatic_scaling:
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static/

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /.*
  script: auto

env_variables:
  MONGO_URI: "mongodb+srv://akash:jXEQJVnnByx7pwbK@cloudlesspay.rwl0a.mongodb.net/cloudlesspay"
  FLASK_SECRET_KEY: "bd13c8d00deb88e1852161cdd4f2363a"
  FLASK_DEBUG: True
  FLASK_JWT_SECRET_KEY: "8f6cf54b330adad9e3d7db1b82cb8bb4"
  JWT_SECRET_KEY: "8f6cf54b330adad9e3d7db1b82cb8bb4"
  SECRET_KEY: "xRvF_59Yq-iPw2KRKkPLD_rw0AI8DhrO6uV6d1zPUS8="
  RAZORPAY_KEY_ID: "rzp_live_yCdMWUSlHAWD7Y"
  RAZORPAY_KEY_SECRET: "zyiQY2H519fEd9Pv06bgvuRY"
  SMTP_USER: "contact@cloudlesspayment.com"
  SMTP_PASSWORD: "gyaq oded egzh ddwp"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: 587